#!/bin/sh

alias ls='ls --color=auto --group-directories-first' \
    lsa='ls -hA --color=auto --group-directories-first' \
    ll='ls -hlF --color=auto --group-directories-first' \
    lla='ls -halF --color=auto --group-directories-first'

alias grep='grep --color=auto' \
    fgrep='fgrep --color=auto' \
    egrep='egrep --color=auto'

alias b='cd $(cat $DIR_BOOKMARKS | fzf)' \
    c='cd $(vifm --choose-dir -)' \
    e='$EDITOR' \
    k='fzf_kill.sh' \
    r='cd $REPOS/$(ls $REPOS | fzf)' \
    ka='killall' \
    xk='xkill' \
    ai='sudo apt-get install' \
    as='apt-cache search' \
    cp='cp -v' \
    mv='mv -v' \
    rm='rm -v' \
    lg='lazygit' \
    df='df --human-readable'

alias ros="ros_source-ws.sh"
