#!/bin/sh

alias ls='ls --color=auto --group-directories-first' \
    lsa='ls -hA --color=auto --group-directories-first' \
    ll='ls -hlF --color=auto --group-directories-first' \
    lla='ls -halF --color=auto --group-directories-first'

alias grep='grep --color=auto' \
    fgrep='fgrep --color=auto' \
    egrep='egrep --color=auto'

alias c='cd $(vifm --choose-dir -)' \
    D='cd $(cat $DIR_BOOKMARKS | fzf)' \
    F='$EDITOR $(cat $FILE_BOOKMARKS | fzf)' \
    L='cd $(find $LATEXDIR -mindepth 1 -maxdepth 2 -type l,d | sort | fzf)' \
    J='cd $(find $PRJDIR -mindepth 1 -maxdepth 1 -type l,d | sort | fzf)' \
    R='cd $(find $REPOSDIR -mindepth 1 -maxdepth 2 -type l,d | sort | fzf)' \
    e='$EDITOR' \
    k='fzf_kill.sh' \
    ka='killall' \
    xk='xkill' \
    ai='sudo apt-get install' \
    aii='fzf_apt.sh' \
    as='apt-cache search' \
    cp='cp -v' \
    mv='mv -v' \
    rm='rm -v' \
    rsync='rsync -v --progress' \
    lg='lazygit' \
    df='df --human-readable' \
    md='media-download.sh' \
    dmenu='dmenu ${DMENU_OPTIONS}'\
    t='task'

alias ros="source ~/Dropbox/scripts/ros_source-ws.sh" \
    cm="catkin_make"
